#!/usr/bin/env python3
# -*- mode: python -*-
# kc: The main command-line kernelcraft frontend
# Copyright © 2022 Andrea Righi
# Licensed under the GPLv2, which is available in the kernelcraft distribution
# as a file called LICENSE with SHA-256 hash:
# 8177f97513213526df2cf6184d8ff986c675afb514d4e68a404010521b880643

# This file is not installed; it's just use to run kernelcraft from inside a
# source distribution.

import sys
if sys.version_info < (3, 3):
    sys.stderr.write('ERROR: kernelcraft requires Python 3.3 or higher\n')
    sys.exit(1)

from kernelcraft import run
exit(run.main())
