#!/usr/bin/env python3
# -*- mode: python -*-
# virtme-mkinitramfs: Generate an initramfs image for virtme
# Copyright © 2019 Marcos Paulo de Souza
# Licensed under the GPLv2, which is available in the virtme distribution
# as a file called LICENSE with SHA-256 hash:
# 8177f97513213526df2cf6184d8ff986c675afb514d4e68a404010521b880643

# This file is not installed; it's just use to run virtme from inside
# a source distribution.

# NOTE: this command is deprecated, please use vng instead.

import sys
from virtme.commands import mkinitramfs

exit(mkinitramfs.main())
