#!/bin/bash
# virtme-runkernel: A silly script to run a kernel image
# Copyright © 2014 Andy Lutomirski
# Licensed under the GPLv2, which is available in the virtme distribution
# as a file called LICENSE with SHA-256 hash:
# 8177f97513213526df2cf6184d8ff986c675afb514d4e68a404010521b880643

# This is a giant hack.  I'll make it better at some point.

tmpfile="`mktemp --tmpdir initramfs.XXXXXXXXXX`"
exec 3<>"$tmpfile"
rm "$tmpfile"

v_mki="$(dirname $0)/virtme-mkinitramfs"
"$v_mki" >&3

if which qemu-kvm &>/dev/null; then
    qemu=qemu-kvm
else
    qemu=qemu
fi

exec "$qemu" -virtfs local,id=rootfs,path=/,security_model=passthrough,mount_tag=hostroot,readonly -initrd /proc/self/fd/3 -machine accel=kvm:tcg -kernel "$@" 
