name: Pylint

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.10", "3.11", "3.12", "3.13", "3.14"]
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v5
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        set -euxo pipefail

        python -m pip install --upgrade pip

        # Both build and runtime deps. This is the price of using pip.
        pip install 'argparse-manpage[setuptools]' argcomplete requests

        pip install  pylint flake8
    - name: Analysing the code with pylint
      run: |
        set -euxo pipefail

        pylint vng '**/*.py'

        flake8 vng
        find . -name '*.py' | xargs flake8
